//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subtlee.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Presenter_HideControls {
            get {
                return ((bool)(this["Presenter_HideControls"]));
            }
            set {
                this["Presenter_HideControls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Main_CacheMostRecentlyUsedSubtitles {
            get {
                return ((bool)(this["Main_CacheMostRecentlyUsedSubtitles"]));
            }
            set {
                this["Main_CacheMostRecentlyUsedSubtitles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Main_CheckCachedMRUSubtitles {
            get {
                return ((bool)(this["Main_CheckCachedMRUSubtitles"]));
            }
            set {
                this["Main_CheckCachedMRUSubtitles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Main_MostRecentlyUsedSubtitleCount {
            get {
                return ((int)(this["Main_MostRecentlyUsedSubtitleCount"]));
            }
            set {
                this["Main_MostRecentlyUsedSubtitleCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>hallo</string>\r\n  <string>test</string>\r\n  <string>xxx</string>\r\n</ArrayOf" +
            "String>")]
        public global::System.Collections.Specialized.StringCollection Main_MostRecentlyUsedSubtitles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Main_MostRecentlyUsedSubtitles"]));
            }
            set {
                this["Main_MostRecentlyUsedSubtitles"] = value;
            }
        }
    }
}
